### ISSUE TITLE
Upper case output sequences

### ISSUE THREAD

**Issue by MafaldaSFerreira** [ODiogoSilva/TriFusion#285]
Include the option to write TriSeq/TriFusion outputs in upper case.

**Comment by ODiogoSilva** [comment]
This feature has been added in the master branch and the pypi package (Since it's still a release candidate, the upgrade must be done with `pip2 install trifusion --pre`).

In TriSeq, this is done via the `-u` or `--uper-case` option. In TriFuson, the option is available in `Process` > `Show additional options` > `Formatting`.

I have also updated the test suite to cover this update, but let me know if run into any issues.
