### ISSUE TITLE
Excluding paralogs

### ISSUE THREAD

**Issue by jmbraverman** [ODiogoSilva/TriFusion#293]
This software seems very useful--up to a point. One needs sequence alignments without paralogs to make trees.  How can those be filtered out?

**Comment by ODiogoSilva** [comment]
Hi @jmbraverman , thank you for your feedback. There are a couple of ways you can filter out paralogs and keep only single-copy orthologs. 

When performing an ortholog search you can change the "Maximum number of gene copies" to 1 in order to keep only single copy genes http://trifusion.readthedocs.io/en/latest/orto_search.html#orthology-search-options.

If you have already performed the search, you can load the resulting group files in the Explore section, apply the filter mentioned above and export the filtered orthologs as protein/DNA http://trifusion.readthedocs.io/en/latest/orto_explore.html#change-the-orthology-filters.

Let me know if you run into any issue!

**Comment by ODiogoSilva** [comment]
Fixed via https://github.com/ODiogoSilva/TriFusion/pull/295
